version: '3.8'

services:
  postgres:
    image: postgres:15.12-alpine3.21
    restart: always
    environment:
      POSTGRES_USER: pitok
      POSTGRES_PASSWORD: pitok234
      POSTGRES_DB: dbname
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "2003:2003"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://pitok:pitok234@postgres:5432/dbname
      - FRONTEND_URL=https://pitok.com

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=https://api.pitok.com

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
  certbot-etc:
