export const env = {
    RECAPTCHA_SECRET_KEY: process.env.RECAPTCHA_SECRET_KEY,
    port: process.env.PORT,
    baseUrl: process.env.BASE_URL,
    emailUser: process.env.EMAIL_USER,
    emailPassword: process.env.EMAIL_PASS,
    frontendUrl: process.env.FRONTEND_URL,
    jwtSecret: process.env.JWT_SECRET,
    mailMailer: process.env.MAIL_MAILER,
    smtpHost: process.env.SMTP_HOST,
    smtpPort: Number(process.env.SMTP_PORT),
    smtpSecure: process.env.SMTP_SECURE === 'true' ? true : false as boolean,
    smtpUser: process.env.SMTP_USER,
    smtpPass: process.env.SMTP_PASS,
    pusherAppId: process.env.PUSHER_APPID,
    pusherKey: process.env.PUSHER_KEY,
    pusherSecreet: process.env.PUSHER_SECREET,
    pusherCluster: process.env.PUSHER_CLUSTER,
    folderKtmId: process.env.GOOGLE_DRIVE_FOLDER_KTM_ID,
    folderProposalId: process.env.GOOGLE_DRIVE_FOLDER_PROPOSAL_ID,
    folderSubmissionId: process.env.GOOGLE_DRIVE_FOLDER_SUBMISSION_ID,
    googleClientEmail: process.env.GOOGLE_CLIENT_EMAIL,
    googlePrivateKey: process.env.GOOGLE_PRIVATE_KEY?.replace(/\\n/g, '\n') || "",
} as const