export const politeknikIndonesia = [
    // Politeknik Negeri
    "Politeknik Elektronika Negeri Surabaya (PENS)",
    "Politeknik Negeri Bandung (Polban)",
    "Politeknik Negeri Jakarta (PNJ)",
    "Politeknik Negeri Semarang (Polines)",
    "Politeknik Negeri Malang (Polinema)",
    "Politeknik Negeri Bali (PNB)",
    "Politeknik Negeri Jember (Polije)",
    "Politeknik Negeri Medan (Polmed)",
    "Politeknik Negeri Padang (PNP)",
    "Politeknik Negeri Lhokseumawe (PNL)",
    "Politeknik Negeri Ujung Pandang (PNUP)",
    "Politeknik Negeri Samarinda (Polnes)",
    "Politeknik Negeri Pontianak (Polnep)",
    "Politeknik Negeri Kupang (PNK)",
    "Politeknik Negeri Manado (Polimdo)",
    "Politeknik Negeri Sriwijaya (Polsri)",
    "Politeknik Negeri Batam (Polibatam)",
    "Politeknik Negeri Cilacap (PNC)",
    "Politeknik Negeri Banyuwangi (Poliwangi)",
    "Politeknik Negeri Indramayu (Polindra)",
    "Politeknik Negeri Subang (Polsub)",
    "Politeknik Negeri Media Kreatif (Polimedia)",
    "Politeknik Pertanian Negeri Payakumbuh (Politani Payakumbuh)",
    "Politeknik Maritim Negeri Indonesia (Polimarin)",
    "Politeknik Manufaktur Negeri Bandung (Polman Bandung)",
    "Politeknik Perkapalan Negeri Surabaya (PPNS)",
    "Politeknik Pertanian Negeri Kupang (Politani Kupang)",
    "Politeknik Negeri Balikpapan (Poltekba)",
    "Politeknik Negeri Madiun (PNM)",
    "Politeknik Negeri Bengkalis (Polbeng)",
    "Politeknik Negeri Nusa Utara (Polnustar)",
    "Politeknik Negeri Lampung (Polinela)",
    "Politeknik Negeri Tanah Laut (Politala)",
    "Politeknik Negeri Fakfak (Polinef)",
    "Politeknik Negeri Ketapang (Politeka)",
    "Politeknik Negeri Nunukan (PNN)",
    "Politeknik Negeri Sambas (Poltesa)",
    "Politeknik Negeri Madura (Poltera)",
    "Politeknik Negeri Banyumas (Polibaya)",
    "Politeknik Negeri Ambon (Polnam)",
    "Politeknik Manufaktur Negeri Bangka Belitung (Polman Babel)",

    // Politeknik Swasta
    "Politeknik Caltex Riau",
    "Politeknik Astra",
    "Politeknik LP3I",
    "Politeknik Piksi Ganesha",
    "Politeknik Gajah Tunggal",
    "Politeknik Pos Indonesia",
    "Politeknik TEDC Cimahi",
    "Politeknik Manufaktur Astra",
    "Politeknik API Yogyakarta",
    "Politeknik Wilmar Bisnis Indonesia",
    "Politeknik Bunda Kandung",
    "Politeknik Bisnis Indonesia",
    "Politeknik Global Indonesia",
    "Politeknik Swadharma",
    "Politeknik Trisila Dharma",
    "Politeknik Tugu Jakarta",
    "Politeknik Pariwisata Batam",
    "Politeknik Bosowa Makassar",
    "Politeknik Jakarta Internasional",
    "Politeknik LPP Yogyakarta",
    "Politeknik AKA Bogor",
    "Politeknik Harapan Bersama",
    "Politeknik Kesehatan Kartini Bali",
    "Politeknik Komputer Niaga LPKIA",
    "Politeknik Darussalam Palembang",
    "Politeknik Bumi Akpelni",
    "Politeknik NSC Surabaya",
    "Politeknik APP Jakarta",
    "Politeknik ATI Makassar",
    "Politeknik Kesehatan Pasapua",
    "Politeknik Krakatau",
    "Politeknik Manufaktur Igasa Pindad",
    "Politeknik Tri Mitra Karya Mandiri",
    "Politeknik AKMB Bandung",
    "Politeknik Garuda Nusantara Bandung"
];
